/**
 * Route-handler tests for the Cortex Analyst cross-check.
 *
 * The governance claims under test: the signed-in persona's role is used for both generation and
 * execution, and Analyst SQL that is not one read-only SEMANTIC_VIEW query is never executed.
 */

import { describe, it, expect, vi, beforeEach } from "vitest"

const querySnowflake = vi.fn()
const runRowsAsRole = vi.fn()
const currentSession = vi.fn()

const getMetricRegistry = vi.fn()
vi.mock("../../lib/sc", () => ({
  querySnowflake: (...a: unknown[]) => querySnowflake(...a),
  getMetricRegistry: () => getMetricRegistry(),
}))
vi.mock("../../lib/persona", () => ({ runRowsAsRole: (...a: unknown[]) => runRowsAsRole(...a) }))
vi.mock("../../lib/session", () => ({ currentSession: () => currentSession(), unmappedCallerResponse: () => null }))

function analystPayload(statement: string | null) {
  const content: unknown[] = [{ type: "text", text: "This is our interpretation" }]
  if (statement) content.push({ type: "sql", statement, confidence: { verified_query_used: null } })
  return {
    status: 200,
    response: { request_id: "r1", message: { content }, response_metadata: { model_names: ["m"] } },
  }
}

function post(body: unknown) {
  return new Request("http://localhost/api/ask/analyst", { method: "POST", body: JSON.stringify(body) })
}

describe("POST /api/ask/analyst", () => {
  beforeEach(() => {
    vi.resetModules()
    querySnowflake.mockReset()
    runRowsAsRole.mockReset()
    currentSession.mockReset()
    getMetricRegistry.mockReset()
    getMetricRegistry.mockResolvedValue([
      { metricId: "supplier_otd_pct", bindings: [{ semanticView: "SC_SUPPLIER" }, { semanticView: "SC_ONTOLOGY_360" }] },
      { metricId: "freight_bill_variance_usd", bindings: [{ semanticView: "SC_LANDED_COST" }, { semanticView: "SC_ONTOLOGY_360" }] },
    ])
    querySnowflake.mockResolvedValue([{ SEMANTIC_VIEW: "SC_SUPPLIER" }, { SEMANTIC_VIEW: "SC_ONTOLOGY_360" }])
  })

  it("generates and executes under the signed-in persona's role", async () => {
    currentSession.mockResolvedValue({ username: "buyer", personaRole: "SC_PROCUREMENT" })
    runRowsAsRole
      .mockResolvedValueOnce({ q: { rows: [{ ASK_CORTEX_ANALYST: analystPayload(
        "SELECT * FROM SEMANTIC_VIEW(supply_chain.semantic.sc_ontology_360 METRICS purchase_order.supplier_otd_pct)\n -- Generated by Cortex Analyst\n;",
      ) }] } })
      .mockResolvedValueOnce({ q: { rows: [{ SUPPLIER_OTD_PCT: 0.875824 }] } })

    const { POST } = await import("../../app/api/ask/analyst/route")
    const res = await POST(post({ question: "What is our supplier on-time delivery?" }))
    const json = await res.json()

    expect(res.status).toBe(200)
    expect(json.answerable).toBe(true)
    expect(json.executedAs).toBe("SC_PROCUREMENT")
    expect(json.rows[0].SUPPLIER_OTD_PCT).toBe(0.875824)
    expect(runRowsAsRole).toHaveBeenCalledTimes(2)
    for (const call of runRowsAsRole.mock.calls) expect(call[0]).toBe("SC_PROCUREMENT")
    expect(runRowsAsRole.mock.calls[1][1][0].sql).not.toContain("Generated by Cortex Analyst")
  })

  it("refuses to execute raw-table SQL from Analyst", async () => {
    currentSession.mockResolvedValue({ username: "planner", personaRole: "SC_PLANNER" })
    runRowsAsRole.mockResolvedValueOnce({ q: { rows: [{ X: analystPayload(
      "WITH x AS (SELECT * FROM SUPPLY_CHAIN.CANONICAL.FCT_SUPPLIER_DELIVERY_LINE) SELECT COUNT(*) FROM x",
    ) }] } })

    const { POST } = await import("../../app/api/ask/analyst/route")
    const json = await (await POST(post({ question: "Is price variance getting worse?" }))).json()

    expect(json.answerable).toBe(false)
    expect(json.rejected).toMatch(/not a single read-only SEMANTIC_VIEW/)
    expect(runRowsAsRole).toHaveBeenCalledTimes(1)
  })

  it("reports a non-SQL Analyst answer as not answerable", async () => {
    currentSession.mockResolvedValue({ username: "planner", personaRole: "SC_PLANNER" })
    runRowsAsRole.mockResolvedValueOnce({ q: { rows: [{ X: JSON.stringify(analystPayload(null)) }] } })

    const { POST } = await import("../../app/api/ask/analyst/route")
    const json = await (await POST(post({ question: "What is our carbon footprint?" }))).json()
    expect(json.answerable).toBe(false)
    expect(json.sql).toBeUndefined()
  })

  it("rejects an empty question", async () => {
    const { POST } = await import("../../app/api/ask/analyst/route")
    const res = await POST(post({ question: " " }))
    expect(res.status).toBe(400)
  })

  it("refuses a metric whose domain the persona is not granted (eval Q53)", async () => {
    currentSession.mockResolvedValue({ username: "buyer", personaRole: "SC_PROCUREMENT" })
    runRowsAsRole.mockResolvedValueOnce({ q: { rows: [{ X: analystPayload(
      "SELECT * FROM SEMANTIC_VIEW(supply_chain.semantic.sc_ontology_360 METRICS landed_cost.freight_bill_variance_usd)",
    ) }] } })

    const { POST } = await import("../../app/api/ask/analyst/route")
    const json = await (await POST(post({ question: "What is our freight bill variance?" }))).json()

    expect(json.answerable).toBe(false)
    expect(json.rejected).toMatch(/not granted the domain/)
    expect(runRowsAsRole).toHaveBeenCalledTimes(1)
  })
})
