/**
 * Allow-list validation for the governance-config fragments that are interpolated into SQL
 * rather than bound (exception predicates and ORDER BY expressions).
 *
 * GOVERNANCE is admin-owned, so these are trusted configuration. This is defence in depth: every
 * token must be a real column of the fact, a number, a quoted literal, an arithmetic/comparison
 * operator or one of a few predicate keywords. Anything else — statement terminators, comments,
 * subqueries, function calls, DDL/DML — is rejected before it reaches Snowflake.
 */

const TOKEN =
  /\s+|'(?:[^'\\]|'')*'|\d+(?:\.\d+)?|<>|!=|<=|>=|[=<>()+\-*/,]|[A-Za-z_][A-Za-z0-9_]*|./gy

const PREDICATE_KEYWORDS = new Set(["AND", "OR", "NOT", "IS", "NULL", "IN", "BETWEEN", "TRUE", "FALSE"])
const ORDER_KEYWORDS = new Set(["ASC", "DESC", "NULLS", "FIRST", "LAST"])

function tokens(sql: string): string[] {
  const out: string[] = []
  TOKEN.lastIndex = 0
  let m: RegExpExecArray | null
  while ((m = TOKEN.exec(sql)) !== null) {
    if (m[0].trim()) out.push(m[0])
    if (TOKEN.lastIndex === sql.length) break
  }
  return out
}

function check(sql: string, columns: Set<string>, keywords: Set<string>, what: string): string {
  const text = String(sql ?? "").trim()
  if (!text || text.length > 500) throw new Error(`${what} failed validation`)
  let depth = 0
  for (const t of tokens(text)) {
    if (/^\s+$/.test(t) || /^\d/.test(t) || /^'/.test(t)) continue
    if (/^(<>|!=|<=|>=|[=<>+\-*/,])$/.test(t)) continue
    if (t === "(") { depth++; continue }
    if (t === ")") { if (--depth < 0) throw new Error(`${what} failed validation`); continue }
    if (/^[A-Za-z_]/.test(t)) {
      const u = t.toUpperCase()
      if (keywords.has(u) || columns.has(u)) continue
    }
    throw new Error(`${what} failed validation at "${t}"`)
  }
  if (depth !== 0) throw new Error(`${what} failed validation`)
  return text
}

export function validateExceptionWhere(where: string, columns: Set<string>): string {
  return check(where, columns, PREDICATE_KEYWORDS, "Exception rule predicate")
}

export function validateOrderBy(orderBy: string, columns: Set<string>): string {
  return check(orderBy, columns, ORDER_KEYWORDS, "Exception rule ORDER BY")
}

/**
 * Metric names a SEMANTIC_VIEW(...) query selects, lower-cased and unqualified
 * (`landed_cost.freight_cost_usd` -> `freight_cost_usd`).
 */
export function referencedMetrics(sql: string): string[] {
  const m = /\bMETRICS\b([\s\S]*?)(?=\bDIMENSIONS\b|\bFACTS\b|\bWHERE\b|\)\s*(?:ORDER|QUALIFY|LIMIT|$)|\)\s*$)/i.exec(sql)
  if (!m) return []
  return m[1]
    .split(",")
    .map((p) => p.trim().replace(/[()]/g, "").split(".").pop()!.trim().toLowerCase())
    .filter((x) => /^[a-z_][a-z0-9_]*$/.test(x))
}

/**
 * Accept Cortex Analyst output only if it is one read-only query over SEMANTIC_VIEW(...).
 * Analyst's trailing "-- Generated by Cortex Analyst" comment and terminator are stripped.
 * Returns null for anything else, so ungoverned SQL is never executed.
 */
export function governedStatement(sql: string): string | null {
  const body = String(sql ?? "")
    .split("\n")
    .filter((l) => !l.trim().startsWith("--"))
    .join("\n")
    .trim()
    .replace(/;\s*$/, "")
  if (!/^(SELECT|WITH)\b/i.test(body)) return null
  if (body.includes(";") || body.includes("/*")) return null
  if (/\b(INSERT|UPDATE|DELETE|MERGE|DROP|CREATE|ALTER|GRANT|REVOKE|TRUNCATE|CALL|COPY|PUT|USE|EXECUTE)\b/i.test(body)) return null
  if (!/SEMANTIC_VIEW\s*\(/i.test(body)) return null
  return body
}

/**
 * "Should we terminate / replace / cut ...?" asks for a decision, not a measurement. A governed
 * metric can inform it but cannot answer it, so the Analyst path declines rather than returning a
 * ranked table that reads as a recommendation (eval Q50).
 */
export function isDecisionQuestion(question: string): boolean {
  return /\b(should|shall|ought)\s+(we|i)\b/i.test(question) || /\b(terminate|fire|blacklist|drop)\s+(a|the|which|our)?\s*(supplier|vendor|carrier)/i.test(question)
}
