#!/usr/bin/env node
/**
 * Regenerate sql/ALL_COMBINED.sql from the numbered sources, in rebuild order.
 *
 *   node scripts/combine-sql.mjs           write the file
 *   node scripts/combine-sql.mjs --check   exit 1 if the committed file is stale (CI)
 *
 * The order is read from the FILES array in scripts/rebuild.mjs rather than duplicated here, so
 * the combined record cannot describe a build order that the rebuild does not actually run.
 * Verify-phase files are excluded: they assert, they do not define.
 */

import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const sqlDir = path.join(root, "sql")
const out = path.join(sqlDir, "ALL_COMBINED.sql")

const rebuild = fs.readFileSync(path.join(root, "scripts", "rebuild.mjs"), "utf8")
const files = [...rebuild.matchAll(/\{\s*file:\s*"([^"]+\.sql)",\s*phase:\s*"(\w+)"/g)]
  .filter((m) => m[2] !== "verify")
  .map((m) => m[1])
if (files.length === 0) throw new Error("No FILES entries found in scripts/rebuild.mjs")

const rule = "-- " + "=".repeat(76)
let text =
  `${rule}\n-- ALL_COMBINED.sql — full DDL/DML record of the SUPPLY_CHAIN database.\n` +
  `-- Auto-generated by scripts/combine-sql.mjs from sql/*.sql in the build order defined by\n` +
  `-- scripts/rebuild.mjs (the FILES array is the authoritative source of order).\n` +
  `-- Do not hand-edit: CI runs \`node scripts/combine-sql.mjs --check\`.\n${rule}\n`

for (const f of files) {
  const body = fs.readFileSync(path.join(sqlDir, f), "utf8").replace(/\r\n/g, "\n")
  text += `\n\n${rule}\n-- FILE: ${f}\n${rule}\n\n${body.trimEnd()}\n`
}

if (process.argv.includes("--check")) {
  const current = fs.existsSync(out) ? fs.readFileSync(out, "utf8").replace(/\r\n/g, "\n") : ""
  if (current !== text) {
    console.error("sql/ALL_COMBINED.sql is stale. Run: node scripts/combine-sql.mjs")
    process.exit(1)
  }
  console.log(`sql/ALL_COMBINED.sql is current (${files.length} files).`)
} else {
  fs.writeFileSync(out, text)
  console.log(`Wrote sql/ALL_COMBINED.sql from ${files.length} files.`)
}
