-- ---------------------------------------------------------------------------
-- 00a — Foundation: database, schemas, roles, warehouse access.
--
-- Run first. Everything else assumes the schemas and roles below exist.
--
-- WHY THE OBJECT GRANTS ARE NOT HERE. Only role creation and container-level
-- access (database, schema, warehouse) live in this file. Grants on tables and
-- semantic views are issued at the end of 00e and 00f, where those objects are
-- created. Future grants would be the tidier option, but they are silently
-- one-directional: a future grant added here does nothing for an object that a
-- later CREATE OR REPLACE re-creates under a different owner, and debugging
-- that costs more than repeating a GRANT next to the CREATE.
--
-- WHY EIGHT ROLES. Five are personas the application switches into per request
-- (lib/persona.ts issues USE ROLE, then USE SECONDARY ROLES NONE so that
-- inherited privileges cannot widen the row scope). Three are owner roles that
-- appear only as METRIC_DEFINITION.owner_role and TARGET_SOURCE text — they name
-- who is accountable for a metric's definition and target. They are real roles
-- rather than free text so that accountability is checkable, not decorative.
-- ---------------------------------------------------------------------------

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS SUPPLY_CHAIN
  COMMENT = 'Supply Chain Ontology. Governed conversational analytics: every number in the app and in the conversational layer resolves to a metric defined in SEMANTIC, registered in GOVERNANCE, and reconcilable to an atomic fact in CANONICAL.';

USE DATABASE SUPPLY_CHAIN;

CREATE SCHEMA IF NOT EXISTS RAW
  COMMENT = 'Landing zone. Synthetic source systems, generated by 00b/00c. Nothing outside CANONICAL reads these tables and no application role is granted on them.';

CREATE SCHEMA IF NOT EXISTS CANONICAL
  COMMENT = 'Atomic-grain conformed facts. One row per business event. These are the reconciliation target: every governed metric carries the SQL that computes it from exactly one of these tables, and the drift test asserts the semantic views agree with that SQL.';

CREATE SCHEMA IF NOT EXISTS SEMANTIC
  COMMENT = 'Semantic views. The only surface the application and Cortex Analyst query. A metric exists here once and is referenced everywhere, so the UI and the conversational layer cannot disagree about what a number means.';

CREATE SCHEMA IF NOT EXISTS GOVERNANCE
  COMMENT = 'Metric registry, ontology catalogue, drift control, persona scoping. Admin-owned: EXCEPTION_WHERE and ORDER_BY from METRIC_EXCEPTION_RULE are interpolated into SQL by the drill-down route, which is safe only because no application role can write here.';

CREATE SCHEMA IF NOT EXISTS UTIL
  COMMENT = 'Reserved for synthetic-data generation helpers. Deliberately empty: the generators in 00c are self-contained and seeded inline, so that no business number depends on a value stored here.';

CREATE SCHEMA IF NOT EXISTS APPS
  COMMENT = 'Holds the deployed APPLICATION SERVICE (see app.yml).';

-- ---------------------------------------------------------------------------
-- Persona roles. Assumed per request by the application.
-- ---------------------------------------------------------------------------

CREATE ROLE IF NOT EXISTS SC_PLANNER
  COMMENT = 'Demand and inventory planning. Sees forecast, inventory and fulfilment.';
CREATE ROLE IF NOT EXISTS SC_PROCUREMENT
  COMMENT = 'Direct materials buying. Sees supplier delivery, fill and purchase price variance.';
CREATE ROLE IF NOT EXISTS SC_LOGISTICS
  COMMENT = 'Outbound transport and cost to serve. Sees fulfilment and landed cost, all regions.';
CREATE ROLE IF NOT EXISTS SC_LOGISTICS_EU
  COMMENT = 'Regional variant of SC_LOGISTICS, row-scoped to EU shipments by a row access policy. Exists to demonstrate that one metric definition can serve different row scopes without being redefined.';
CREATE ROLE IF NOT EXISTS SC_ONTOLOGY_STEWARD
  COMMENT = 'Owns the semantic layer. The only persona that sees every view, the drift control and the consistency evidence.';

-- ---------------------------------------------------------------------------
-- Owner roles. Named as accountable parties in the metric registry.
-- ---------------------------------------------------------------------------

CREATE ROLE IF NOT EXISTS SC_PROCUREMENT_ANALYST
  COMMENT = 'Accountable for the definition and target of the supplier metrics.';
CREATE ROLE IF NOT EXISTS SC_LOGISTICS_ANALYST
  COMMENT = 'Accountable for the definition and target of the fulfilment and landed-cost metrics.';
CREATE ROLE IF NOT EXISTS SC_PLANNING_ANALYST
  COMMENT = 'Accountable for the definition and target of the inventory and demand metrics.';

-- ---------------------------------------------------------------------------
-- Container access and warehouse usage.
--
-- RAW is deliberately absent: a persona that could read RAW could compute a
-- metric by hand and get a different answer, which is the failure this project
-- exists to prevent. Personas reach atomic rows only through CANONICAL, and only
-- via the drill-down, which is constrained by METRIC_EXCEPTION_RULE.
-- ---------------------------------------------------------------------------

USE ROLE ACCOUNTADMIN;

-- MONTY needs to be able to assume every persona to exercise the app locally.
GRANT ROLE SC_PLANNER            TO USER MONTY;
GRANT ROLE SC_PROCUREMENT        TO USER MONTY;
GRANT ROLE SC_LOGISTICS          TO USER MONTY;
GRANT ROLE SC_LOGISTICS_EU       TO USER MONTY;
GRANT ROLE SC_ONTOLOGY_STEWARD   TO USER MONTY;
GRANT ROLE SC_PROCUREMENT_ANALYST TO USER MONTY;
GRANT ROLE SC_LOGISTICS_ANALYST  TO USER MONTY;
GRANT ROLE SC_PLANNING_ANALYST   TO USER MONTY;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_PLANNER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_PROCUREMENT;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_LOGISTICS;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_LOGISTICS_EU;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_ONTOLOGY_STEWARD;

GRANT USAGE ON DATABASE SUPPLY_CHAIN TO ROLE SC_PLANNER;
GRANT USAGE ON DATABASE SUPPLY_CHAIN TO ROLE SC_PROCUREMENT;
GRANT USAGE ON DATABASE SUPPLY_CHAIN TO ROLE SC_LOGISTICS;
GRANT USAGE ON DATABASE SUPPLY_CHAIN TO ROLE SC_LOGISTICS_EU;
GRANT USAGE ON DATABASE SUPPLY_CHAIN TO ROLE SC_ONTOLOGY_STEWARD;

GRANT USAGE ON SCHEMA SUPPLY_CHAIN.SEMANTIC TO ROLE SC_PLANNER;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN.SEMANTIC TO ROLE SC_PROCUREMENT;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN.SEMANTIC TO ROLE SC_LOGISTICS;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN.SEMANTIC TO ROLE SC_LOGISTICS_EU;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN.SEMANTIC TO ROLE SC_ONTOLOGY_STEWARD;

GRANT USAGE ON SCHEMA SUPPLY_CHAIN.GOVERNANCE TO ROLE SC_PLANNER;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN.GOVERNANCE TO ROLE SC_PROCUREMENT;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN.GOVERNANCE TO ROLE SC_LOGISTICS;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN.GOVERNANCE TO ROLE SC_LOGISTICS_EU;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN.GOVERNANCE TO ROLE SC_ONTOLOGY_STEWARD;

GRANT USAGE ON SCHEMA SUPPLY_CHAIN.CANONICAL TO ROLE SC_PLANNER;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN.CANONICAL TO ROLE SC_PROCUREMENT;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN.CANONICAL TO ROLE SC_LOGISTICS;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN.CANONICAL TO ROLE SC_LOGISTICS_EU;
GRANT USAGE ON SCHEMA SUPPLY_CHAIN.CANONICAL TO ROLE SC_ONTOLOGY_STEWARD;

-- The steward reads INFORMATION_SCHEMA.SEMANTIC_* through the ontology views.
GRANT USAGE ON SCHEMA SUPPLY_CHAIN.APPS TO ROLE SC_ONTOLOGY_STEWARD;
